apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: pgsql-app1-prod-4plst-maintenance-role
spec:
  forProvider:
    manifest:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        creationTimestamp: null
        name: crossplane:appcat:job:postgres:maintenance
        namespace: vshn-postgresql-pgsql-app1-prod-4plst
      rules:
      - apiGroups:
        - stackgres.io
        resources:
        - sgdbops
        verbs:
        - delete
        - create
        - get
        - list
        - watch
      - apiGroups:
        - stackgres.io
        resources:
        - sgclusters
        verbs:
        - list
        - get
      - apiGroups:
        - vshn.appcat.vshn.io
        resources:
        - vshnpostgresqls
        verbs:
        - get
        - update
  providerConfigRef:
    name: kubernetes
