apiVersion: vshn.appcat.vshn.io/v1
kind: XVSHNPostgreSQL
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"vshn.appcat.vshn.io/v1","kind":"VSHNPostgreSQL","metadata":{"annotations":{},"name":"widera-test-cluster-always-true","namespace":"widera-testing"},"spec":{"parameters":{"backup":{"deletionProtection":false}},"writeConnectionSecretToRef":{"name":"postgres-creds-connection-cluster-always-true"}}}
  creationTimestamp: "2023-09-18T09:01:28Z"
  finalizers:
  - composite.apiextensions.crossplane.io
  generateName: widera-test-cluster-always-true-
  generation: 5
  labels:
    crossplane.io/claim-name: widera-test-cluster-always-true
    crossplane.io/claim-namespace: widera-testing
    crossplane.io/composite: widera-test-cluster-always-true-78vgw
  name: widera-test-cluster-always-true-78vgw
  resourceVersion: "7100"
  uid: 58cb1fcf-6c0c-4d61-bc6a-b4e7cab048dd
spec:
  claimRef:
    apiVersion: vshn.appcat.vshn.io/v1
    kind: VSHNPostgreSQL
    name: widera-test-cluster-always-true
    namespace: widera-testing
  compositionRef:
    name: vshnpostgres.vshn.appcat.vshn.io
  compositionRevisionRef:
    name: vshnpostgres.vshn.appcat.vshn.io-db33d25
  compositionUpdatePolicy: Automatic
  parameters:
    backup:
      deletionProtection: false
      deletionRetention: 7
      retention: 6
      schedule: 43 0 * * *
    encryption: {}
    instances: 1
    maintenance:
      dayOfWeek: wednesday
      timeOfDay: "01:43:08"
    monitoring: {}
    network:
      ipFilter:
      - 0.0.0.0/0
      serviceType: ClusterIP
    replication: {}
    restore: {}
    scheduling: {}
    service:
      majorVersion: "15"
      serviceLevel: besteffort
    size:
      plan: standard-2
      requests: {}
    updateStrategy:
      type: Immediate
  resourceRefs:
  - apiVersion: appcat.vshn.io/v1
    kind: XObjectBucket
    name: widera-test-cluster-always-true-78vgw
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: ns-observer-widera-test-cluster-always-true-78vgw
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: vshn-postgresql-widera-test-cluster-always-true-78vgw
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-certificate
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-cluster
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-connection
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-localca
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-maintenance-role
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-maintenance-rolebinding
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-maintenance-secret
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-maintenance-serviceaccount
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-maintenancejob
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-network-policy
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-object-storage
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-pgconf
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-podmonitor
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-primary-service
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-profile
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-prometheusrule
  - apiVersion: kubernetes.crossplane.io/v1alpha1
    kind: Object
    name: widera-test-cluster-always-true-78vgw-service-rolebinding
  writeConnectionSecretToRef:
    name: 58cb1fcf-6c0c-4d61-bc6a-b4e7cab048dd
    namespace: syn-crossplane
status:
  certificateConditions:
  - lastTransitionTime: "2023-09-18T09:01:32Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-09-18T09:01:32Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  conditions:
  - lastTransitionTime: "2023-09-18T09:01:38Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-09-18T09:04:14Z"
    reason: Available
    status: "True"
    type: Ready
  connectionDetails:
    lastPublishedTime: "2023-09-18T09:04:14Z"
  instanceNamespace: vshn-postgresql-widera-test-cluster-always-true-78vgw
  localCAConditions:
  - lastTransitionTime: "2023-09-18T09:01:31Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-09-18T09:01:31Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  namespaceConditions:
  - lastTransitionTime: "2023-09-18T09:01:31Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-09-18T09:01:31Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  networkPolicyConditions:
  - lastTransitionTime: "2023-09-18T09:01:31Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-09-18T09:01:31Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  pgclusterConditions:
  - lastTransitionTime: "2023-09-18T09:02:41Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-09-18T09:02:41Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  pgconfigConditions:
  - lastTransitionTime: "2023-09-18T09:01:32Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-09-18T09:01:32Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  profileConditions:
  - lastTransitionTime: "2023-09-18T09:01:32Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-09-18T09:01:32Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  secretConditions:
  - lastTransitionTime: "2023-09-18T09:03:28Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2023-09-18T09:03:28Z"
    reason: Available
    status: "True"
    type: Ready