---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  labels:
    name: provider-cloudscale
  name: provider-cloudscale
spec:
  package: ghcr.io/vshn/provider-cloudscale/provider:v0.5.0
