---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  labels:
    name: provider-kubernetes
  name: provider-kubernetes
spec:
  controllerConfigRef:
    name: kubernetes
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.9.0
