---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: appcat-apiserver
rules:
  - apiGroups:
      - ""
    resourceNames:
      - extension-apiserver-authentication
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.crossplane.io
    resources:
      - compositions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appcat-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appcat-apiserver
subjects:
  - kind: ServiceAccount
    name: appcat-apiserver
    namespace: appcat
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appcat-apiserver
  namespace: appcat
---
apiVersion: v1
kind: Service
metadata:
  name: appcat
  namespace: appcat
  labels:
    api: appcat
    apiserver: "true"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    api: appcat
    apiserver: "true"

