apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appcat-sli-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appcat-sli-exporter
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
