
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.api.appcat.vshn.io
  labels:
    api: appcat
    apiserver: "true"
spec:
  version: v1
  group: api.appcat.vshn.io
  groupPriorityMinimum: 2000
  service:
    name: appcat
    namespace: default
    port: 443
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyVENDQXBXZ0F3SUJBZ0lVVFlnTXlUb2RtZ3RWSS9Bak1yQUxjbzl4M05vd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pqRUxNQWtHQTFVRUJoTUNkVzR4Q3pBSkJnTlZCQWdNQW5OME1Rb3dDQVlEVlFRSERBRnNNUW93Q0FZRApWUVFLREFGdk1Rc3dDUVlEVlFRTERBSnZkVEVsTUNNR0ExVUVBd3djWVhCd1kyRjBMV05sY25ScFptbGpZWFJsCkxXRjFkR2h2Y21sMGVUQWVGdzB5TXpBeE1qUXhNREF4TlRWYUZ3MHlOREF4TWpReE1EQXhOVFZhTUdZeEN6QUoKQmdOVkJBWVRBblZ1TVFzd0NRWURWUVFJREFKemRERUtNQWdHQTFVRUJ3d0JiREVLTUFnR0ExVUVDZ3dCYnpFTApNQWtHQTFVRUN3d0NiM1V4SlRBakJnTlZCQU1NSEdGd2NHTmhkQzFqWlhKMGFXWnBZMkYwWlMxaGRYUm9iM0pwCmRIa3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEUVc3UzBSblkvUEcreXBQbWUKWDdWbzZJTFIzaTNPdzF4aCswcDU3cXlFZmJuZURyMVRiM0hVNjVtbVl5VDZUSVk5T1RKY1E1Yys4ZER5TlpkNApyYW1tcENxQ0MxdU1XNXd1RWpWbTNGSnIvYlJaSThCcXhENGZmcnNnc3Roc3BSem9WbkVMeUhnZkVJa3cwMi9JClVUTEtYd3FqMVNDS0YxcjZ3UE1ORENjREdqV01kY2hFYkdyNWx4VDE4UEdrMVlIYXJHSXk5L01weVhwYW9yREUKc2ErMnZONjd1bDl1REN3bUJqZ3I5aUU1bEl2bmc2OXQzdDlOcWhqcDlyWmpqQTQ2aVoyZUthOFRIRnRvM2t5UwpRL29XYWVYMnhtdUNvZWI5WUZpOHF4Qm13d2oyck1aa2RKSUNJUUE4TkVhMVRUc1FPM2oxSjl4dWdzSmUzRUFHClVPWkhBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlE1VVY5bFFzUWtHZFRXanRYTllobTR1MUg3dHpBZkJnTlYKSFNNRUdEQVdnQlE1VVY5bFFzUWtHZFRXanRYTllobTR1MUg3dHpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQi9KL2FBczRuenJmTnpIc0U2TWFCUUN0UE85OG9qZy9jcTkyeFFBKzdaCmtadGQ5aENBZ3V3TllBa1ZvNVIwYlNpSTFCSmFZL3paMy80MTFiNVdsdytzakJSYUx4RzgzanR6OFkyOXRXVGgKVm5lU1JkWlFDdnU2MlV6ZnFXekY1Tzdtb044c0RPZVRDa1VnSWF4TDg0QUJCdlF5MW5CbzhJSXYxZDFGNWkyVgp5N3Q4SmRnd29XRUprTFA5MEVSMmpuNndMN21ZN0VPZHU5eEJEclVhY3lHYndnTVUyK2hXYnhSYXhzd0J0ZjA5CmlNOHAzaG9CMG54aDJ0dWZCTHlKVjA3QUVhdEFZb0pzbWJPcStDSlhzYUxucXZOUEQzWXZ1S2ZQVEhIa3BFVVoKNEFRdWl1eUppWktyRitnRUJFNy9ua2NDVU9kc0p0Wkh2SnI3cHV3S1J5Zm4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
---
