---
apiVersion: v1
kind: Service
metadata:
  name: appcat
  namespace: default
  labels:
    api: appcat
    apiserver: "true"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    api: appcat
    apiserver: "true"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appcat-apiserver-auth-reader
rules:
  - apiGroups:
      - ""
    resourceNames:
      - extension-apiserver-authentication
    resources:
      - configmaps
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appcat-apiserver-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appcat-apiserver-auth-reader
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appcat-apiserver-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appcat-controller
  namespace: default
rules:
  - apiGroups:
      - 'appcat.vshn.io'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - 'configmaps'
      - 'namespaces'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - '*'
    verbs:
      - 'list'
      - 'watch'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appcat-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appcat-controller
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
