---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: appcat-controllers
        path: /validate-vshn-appcat-vshn-io-v1-vshnpostgresql
    failurePolicy: Fail
    name: postgresql.vshn.appcat.vshn.io
    rules:
      - apiGroups:
          - vshn.appcat.vshn.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - vshnpostgresqls
    sideEffects: None
