---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate--v1-namespace
    failurePolicy: Fail
    name: namespace.vshn.appcat.vshn.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - DELETE
        resources:
          - namespaces
        scope: Cluster
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate--v1-persistentvolumeclaim
    failurePolicy: Fail
    name: pvc.vshn.appcat.vshn.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - DELETE
        resources:
          - persistentvolumeclaims
        scope: Namespaced
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-appcat-vshn-io-v1-xobjectbucket
    failurePolicy: Fail
    name: objectbuckets.vshn.appcat.vshn.io
    rules:
      - apiGroups:
          - appcat.vshn.io
        apiVersions:
          - v1
        operations:
          - DELETE
        resources:
          - xobjectbuckets
        scope: Cluster
    sideEffects: None
