apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appcat-controller-leader-election-rolebinding
  namespace: appcat-controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: appcat-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: appcat-controller
    namespace: appcat-controllers
