---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate--v1-namespace
  failurePolicy: Fail
  name: namespace.vshn.appcat.vshn.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - namespaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-appcat-vshn-io-v1-objectbucket
  failurePolicy: Fail
  name: objectbuckets.vshn.appcat.vshn.io
  rules:
  - apiGroups:
    - appcat.vshn.io
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - objectbuckets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vshn-appcat-vshn-io-v1-vshnpostgresql
  failurePolicy: Fail
  name: postgresql.vshn.appcat.vshn.io
  rules:
  - apiGroups:
    - vshn.appcat.vshn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - vshnpostgresqls
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate--v1-persistentvolumeclaim
  failurePolicy: Fail
  name: pvc.vshn.appcat.vshn.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - persistentvolumeclaims
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vshn-appcat-vshn-io-v1-vshnkeycloak
  failurePolicy: Fail
  name: vshnkeycloak.vshn.appcat.vshn.io
  rules:
  - apiGroups:
    - vshn.appcat.vshn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - vshnkeycloaks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vshn-appcat-vshn-io-v1-vshnmariadb
  failurePolicy: Fail
  name: vshnmariadb.vshn.appcat.vshn.io
  rules:
  - apiGroups:
    - vshn.appcat.vshn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - vshnmariadbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vshn-appcat-vshn-io-v1-vshnminio
  failurePolicy: Fail
  name: vshnminio.vshn.appcat.vshn.io
  rules:
  - apiGroups:
    - vshn.appcat.vshn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - vshnminios
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vshn-appcat-vshn-io-v1-vshnnextcloud
  failurePolicy: Fail
  name: vshnnextcloud.vshn.appcat.vshn.io
  rules:
  - apiGroups:
    - vshn.appcat.vshn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - vshnnextclouds
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vshn-appcat-vshn-io-v1-vshnredis
  failurePolicy: Fail
  name: vshnredis.vshn.appcat.vshn.io
  rules:
  - apiGroups:
    - vshn.appcat.vshn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - vshnredis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-appcat-vshn-io-v1-xobjectbucket
  failurePolicy: Fail
  name: xobjectbuckets.vshn.appcat.vshn.io
  rules:
  - apiGroups:
    - appcat.vshn.io
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - xobjectbuckets
  sideEffects: None
